proyecto_inmuebles/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from gestion_inmuebles.views import registro, pagina_principal, profile, inmuebles,inmuebles_detalle, inmuebles_agregar, inmuebles_actualizar,inmuebles_eliminar, agregar_foto_a_inmueble, inmuebles_foto_eliminar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',pagina_principal, name='inicio'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'),name='logout'),
    path('registro/',registro, name='register'),
    path('profile/',profile,name='profile'),
    path('inmuebles/',inmuebles,name='inmuebles'),
    path('inmuebles/agregar/',inmuebles_agregar,name='inmuebles_agregar'),
    path('inmuebles/<int:id_inmueble>',inmuebles_detalle,name='inmuebles_detalle'),
    path('inmuebles/<int:id_inmueble>/actualizar',inmuebles_actualizar,name='inmuebles_actualizar'),
    path('inmuebles/<int:id_inmueble>/eliminar',inmuebles_eliminar,name='inmuebles_eliminar'),
    path('inmuebles/<int:id_inmueble>/fotos/agregar',agregar_foto_a_inmueble,name='agregar_foto'),
    path('inmuebles/<int:id_inmueble>/fotos/<int:id_foto>/eliminar',inmuebles_foto_eliminar,name='eliminar_foto'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion_inmuebles/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import ValidationError
import uuid
from django.utils.timezone import now
from django.contrib.auth.models import Group
# Create your models here.

TIPO_USUARIO = [
    ('arrendador','Arrendador'),
    ('arrendatario','Arrendatario'),
    ('administrador','Administrador')
]
class Usuario(AbstractUser):
    nombres  = models.CharField(max_length=150, null=False, blank=False)
    apellidos = models.CharField(max_length=150, null=False, blank=False)
    rut = models.CharField(max_length=10, null=False, blank=False, unique=True)
    direccion = models.CharField(max_length=250, blank=True, null=True)
    telefono = models.CharField(max_length=20, blank=True, null=True)
    # email desde AbstracUser
    tipo_usuario = models.CharField(max_length=50, choices=TIPO_USUARIO, default='arrendatario')
    is_active = models.BooleanField(default=True, editable=False)
    deleted_at = models.DateTimeField(blank=True,null=True, editable=False)
    
    def delete(self, *args, **kwargs):
        self.is_active = False
        self.deleted_at = now()
        if self.inmuebles.exists():
            for inmueble in self.inmuebles.all():
                inmueble.delete()
        self.save()
 
    def __str__(self):
        if self.is_superuser:
            return self.username
        else:
            return self.nombres
    
    def save(self, *args, **kwargs):
        # Asigna un RUT único si el usuario es un superusuario y el RUT está vacío
        if self.is_superuser and not self.rut:
            self.tipo_usuario = 'administrador'  # Asignamos el tipo 'admin' para superusuarios
            self.rut = str(uuid.uuid4())[:9]  # Generamos un RUT único de 12 caracteres
        super().save(*args, **kwargs)



class Region(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    
    def __str__(self):
        return self.nombre
class Comuna(models.Model):
    nombre = models.CharField(max_length=100, unique=True)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='comunas')
    
    class Meta:
        ordering = ["nombre"]
    
    
    def __str__(self):
        return self.nombre


TIPO_INMUEBLES = [
    ('casa','Casa'),
    ('departamento','Departamento'),
    ('parcela','Parcela'),
]

class Inmueble(models.Model):
    nombre = models.CharField(max_length=200)
    descripcion = models.TextField()
    m2_construidos = models.FloatField()
    m2_totales = models.FloatField()
    estacionamientos = models.IntegerField()
    habitaciones = models.IntegerField()
    banos = models.IntegerField()
    direccion = models.CharField(max_length=200)
    #comuna = models.CharField(max_length=100)
    comuna = models.ForeignKey(Comuna,on_delete=models.CASCADE,null=True,blank=True)
    tipo_inmueble = models.CharField(max_length=50, choices=TIPO_INMUEBLES)
    precio_mensual = models.DecimalField(max_digits=10, decimal_places=2)
    dueño = models.ForeignKey(Usuario, on_delete=models.CASCADE,limit_choices_to={'tipo_usuario': 'arrendador'},related_name='inmuebles')
    is_active = models.BooleanField(default=True, editable=False)
    deleted_at = models.DateTimeField(blank=True,null=True, editable=False)
    
    # def delete(self, *args, **kwargs):
    #     self.is_active = False
    #     self.deleted_at = now()
    #     self.save()
    
    # def clean(self):
    #     if self.dueño and self.dueño.tipo_usuario != 'arrendador':
    #         raise ValidationError("El usuario seleccionado no es un arrendador.")
    
    def __str__(self):
        return self.nombre


class Foto(models.Model):
    descripcion = models.CharField(max_length=255, blank=True, null=True, default='')
    foto = models.ImageField(upload_to='inmuebles/')
    inmueble = models.ManyToManyField(Inmueble,related_name='fotos')

templates/agregar_foto.html
{% extends 'layout/base.html' %}


{% block title %}
    Agregar Foto
{% endblock title %}
    

{% block content %}
<main class="container">
    <div class="row">
        <div class="col">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>Agregar Foto</h3>
                {{ form.as_p }}
            
                <button type="submit">Agregar</button>
            </form>
        </div>
        <div class="col">
            <article class="p-0 my-2">
                <h2>Fotos del inmueble</h2>
                <ul class="list-group">
                    {% if inmueble.fotos.all %}
                        {% for foto in inmueble.fotos.all %}
                            <li class="list-group-item">
                                <img class="" src="{{foto.foto.url}}" width="200px" alt="{{foto.descripcion}}" srcset="">
                                <a class="btn btn-outline-danger" href="{% url 'eliminar_foto' id_inmueble=inmueble.id id_foto=foto.id  %}">eliminar</a>

                            </li>
                        {% endfor %}
                    {% else %}
                    <li class="list-group-item">
                        <p>NO hay ninguna foto agregar aun</p>
                    </li>
                    {% endif %}
                    
                </ul>
            </article>
            
        </div>
    </div>
</main>



{% endblock content %}
    

templates/index.html
{% extends 'layout/base.html' %}


{% block title %}
    Inicio Inmuebles
{% endblock title %}
    

{% block content %}

<main>
    <section class="hero-section">
        <h1>
            Encuentra el inmueble de tus sueños
        </h1>
        <button>
            <a href="{% url 'inmuebles' %}">
                Buscar
            </a>
        </button>
    </section>
</main>

{% endblock content %}
    

templates/inmuebles.html
{% extends 'layout/base.html' %}

{% block title %}
Inmuebles
{% endblock title %}
{% load humanize %}

{% block content %}
<style>
    .card-inmueble {
        transition: all 0.3s ease;
    }

    .card-inmueble:hover {
        /* box-shadow:  3px 3px 7px rgba(red, 0, 0, 5) ; */
        box-shadow: 0 0.1rem 0.5rem rgba(0, 0, 0, 0.3);
        scale: 1.02;
    }
</style>
<main class="container mb-5">  
    <h1>Lista de Inmuebles</h1>
    <div class="row">
        <form id="filter-form" action="{% url 'inmuebles' %}" method="get">
            <div class="row">
                <div class="col col-md-4">
                    <select class="form-select" name="region" id="region-select">
                        <option value="" selected>Seleccione Region</option>
                        {% for region in regiones %}
                        <option 
                        value="{{ region.nombre }}" 
                        {% if request.GET.region == region.nombre %} selected {% endif %}>
                            {{ region.nombre }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                
                <div class="col col-md-4">
                    <select class="form-select" name="comuna" id="comuna-select">
                        <option value="" selected>Seleccione comuna</option>
                        {% for comuna in comunas %}
                        <option 
                        value="{{ comuna.nombre }}" 
                        {% if request.GET.comuna == comuna.nombre %} selected {% endif %}>
                            {{ comuna.nombre }}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col">
                    <a class="btn btn-outline-secondary " href="{% url 'inmuebles' %}">Borrar filtros</a>
                </div>
            </div>
            <!-- <div class="col">
                <button class="btn btn-primary my-1"  type="submit">Filtrar</button>
            </div> -->
        </form>

    </div>
    <!-- style="width: 18rem;" -->
    <div class="row">
        {% for inmueble in inmuebles %}
        <div class="col col-lg-3 col-md-4 col-sm-12  mt-4">
            {% include 'components/inmueble_card.html' %}
        </div>
        {% endfor %}
    </div>
</main>

<script>
    document.getElementById('region-select').addEventListener('change', function() {
        document.getElementById('filter-form').submit(); // Envía el formulario automáticamente
    });
    document.getElementById('comuna-select').addEventListener('change', function() {
        document.getElementById('filter-form').submit(); // Envía el formulario automáticamente
    });
</script>

{% endblock content %}

templates/inmuebles_actualizar.html
{% extends 'layout/base.html' %}


{% block title %}
    Agregar Inmueble
{% endblock title %}
    

{% block content %}
<main class="container">
    <div class="row">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-primary my-1" type="submit">Guardar</button>
            <a href="{% url 'profile' %}" class="btn btn-outline-secondary m-1">Cancelar</a>
        </form>
        
    </div>
    <div class="row">
        <div class="col-1 ms-auto mb-5">
            <a class="btn btn-danger my-1" href="{% url 'inmuebles_eliminar' id_inmueble=inmueble.id %}">ELIMINAR</a>

        </div>
    </div>
</main>



{% endblock content %}
    

templates/inmuebles_agregar.html
{% extends 'layout/base.html' %}


{% block title %}
    Agregar Inmueble
{% endblock title %}
    

{% block content %}
<main class="container">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-primary my-1" type="submit">Guardar</button>
    </form>
</main>



{% endblock content %}
    

templates/inmuebles_detalle.html
{% extends 'layout/base.html' %}


{% block title %}
Detalle Inmueble
{% endblock title %}
<!-- {% load humanize %} -->

{% block content %}
{% load static %}


<!-- {% for foto in inmueble.fotos.all %}
    <img src="{{foto.foto.url}}" alt="{{foto.descripcion}}">
    <p>foto.url{{foto.url}}</p>
    <p>foto.foto.url{{foto.foto.url}}</p>
{% endfor %} -->

<main class="container ">
    <section>
        <div class="row">
            <h2 class="display-5"> {{inmueble.nombre}} </h2>
            <div class="col">
                <article class="border rounded-3 my-2">
                    <div class="row">
                        <div class="col-sm-7">
                            <div class="card m-2 p-2">
                                <div class="row">
                                    <span class="display-2">${{inmueble.precio_mensual|floatformat}}</span>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        <p class="display-6 mb-0">{{inmueble.banos}} <img src="{% static 'bath.svg' %}"
                                                alt="Baños icon" width="35em"></p>
                                        <p class="fs-6">Baños</p>
                                    </div>
                                    <div class="col">
                                        <p class="display-6 mb-0">{{inmueble.habitaciones}} <img
                                                src="{% static 'bed.svg' %}" alt="Habitaciones icon" width="35em"></p>
                                        <p class="fs-6">Habitaciones</p>
                                    </div>
                                    <div class="col">
                                        <p class="display-6 mb-0">{{inmueble.estacionamientos}} <img
                                                src="{% static 'car2.svg' %}" alt="Estacionamientos icon" width="35em">
                                        </p>
                                        <p class="fs-6">Estacionamientos</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-5">
                            <div class="m-2 p-2">
                                <div class="row">
                                    <div class="col">
                                        <p class="display-6 mb-0">
                                            <img src="{% static 'triangulo.svg' %}" alt="Baños icon" width="30em">
                                            {{inmueble.m2_construidos}}
                                        </p>
                                        <p class="fs-6">m² Construidos</p>
                                    </div>
                                    <div class="col">
                                        <p class="display-6 mb-0">
                                            <img src="{% static 'triangulo.svg' %}" alt="Baños icon" width="30em">
                                            {{inmueble.m2_totales}}
                                        </p>
                                        <p class="fs-6">m² Totales</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <p class="fs-5"><img src="{% static 'map.svg' %}" alt="map point icon" width="20em"> {{inmueble.direccion}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <!-- carrusel de imagenes -->
                <article class="card">
                    <div id="carouselExampleIndicators" class="carousel slide">
                        <!-- <div class="carousel-indicators">
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0"
                                class="active" aria-current="true" aria-label="Slide 1"></button>
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                                aria-label="Slide 2"></button>
                            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                                aria-label="Slide 3"></button>
                        </div> -->
                        <div class="carousel-inner overflow-hidden" style=" width:100%; height: 600px !important;">
                            <!-- <div class="carousel-item active">
                                <img src="https://placehold.co/900x600" class="d-block w-100" alt="...">
                            </div> -->
                            
                            {% if inmueble.fotos.all %}
                                {% for foto in inmueble.fotos.all %}
                                    <div class="carousel-item active">
                                        <img src="{{foto.foto.url}}" class="d-block w-100 overflow-hidden" alt="{{foto.descripcion}}">
                                    </div>
                                {% endfor %}
                            {% else %}
                                <div class="carousel-item active">
                                    <img src="{% static 'img/sinimage.webp' %}" class="d-block w-100" alt="...">
                                </div>
                                <div class="carousel-item active">
                                    <img src="{% static 'img/sinimage.webp' %}" class="d-block w-100" alt="...">
                                </div>
                            {% endif %}
                                
                            
>
                        </div>
                        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                            data-bs-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                            data-bs-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                    </div>
                </article>
            </div>
            <div class="col-sm-4">
                <article class="card p-3">
                    <div class="row">
                        <p class="fs-6 mb-0">Dueño:</p>
                        <p class="fs-4">{{inmueble.dueño.nombres}} {{inmueble.dueño.apellidos}}</p>
                        <button class="btn btn-outline-primary">Contactar</button>
                    </div>
                </article>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <article class="card p-3 my-3">
                    <p>{{inmueble.descripcion}}</p>
                </article>
            </div>
        </div>
    </section>
</main>

{% endblock content %}

templates/login.html
{% extends 'layout/base.html' %}


{% block title %}
Inicio de sesion - Inmuebles
{% endblock title %}


{% block content %}
<main class="d-flex justify-content-center align-items-center">
    <article class="card w-25 p-5 m-auto rounded-4">
        <h2>Iniciar Sesión</h2>
        <form method="post">
            {% csrf_token %}
            <fieldset class="my-1">
                <label class="form-label" for="{{form.username.id_for_label}}">Nombre de usuario:</label>
                <input class="form-control" type="text" id="{{form.username.id_for_label}}" name="{{form.username.name}}">
            </fieldset>
            <fieldset class="my-1">
                <label class="form-label" for="{{form.username.id_for_label}}">Contraseña:</label>
                <input class="form-control"  type="password" id="{{form.password.id_for_label}}" name="{{form.password.name}}">
            </fieldset>
            <button class="btn btn-primary my-1" type="submit">Ingresar</button>
        </form>
    </article>

</main>
{% endblock content %}

templates/logout.html
<h2>Cerrar Sesión</h2>
<p>Has cerrado sesión exitosamente.</p>

templates/profile.html
{% extends 'layout/base.html' %}

{% block title %}
Perfil de usuario
{% endblock title %}


{% block content %}
<main class="container">
    <div class="row">
        <div class="col-sm-6">
            <div class="row">
                {% if perms.gestion_inmuebles.add_inmueble %}
                <a href="{% url 'inmuebles_agregar' %}" class="btn btn-primary" aria-current="page">Agregar Inmueble</a>
                {% endif %}
            </div>
            <div class="row">
                <article class="p-0 my-2">
                    <ul class="list-group">
                        {% for inmueble in inmuebles %}
                            <li class="list-group-item">
                                <p>{{inmueble}}</p>
                
                                <a class="btn btn-outline-primary" href="{% url 'inmuebles_detalle' id_inmueble=inmueble.id %}">Ver</a>
                                <a class="btn btn-outline-warning" href="{% url 'inmuebles_actualizar' id_inmueble=inmueble.id %}">Modificar</a>
                                <a class="btn btn-outline-info" href="{% url 'agregar_foto' id_inmueble=inmueble.id %}">Agregar/Eliminar Fotos</a>

                            </li>
                        {% endfor %}
                            
                    </ul>
                </article>
            </div>
            
        </div>
        <div class="col-sm-6">
            <article class="card p-2 rounded-4">
                <!-- <p class="display-2">{{user.username|title}}</p> -->
                    <h2>Datos de usuario</h2>
                    <form method="post">
                        {% csrf_token %}
                        {% if messages %}
                        {{messages.error}}
                        {% endif %}
                        <fieldset class="my-1">
                            <label class="form-label" for="{{form.nombres.id_for_label}}">Nombres:</label>
                            <input class="form-control" type="text" id="{{form.nombres.id_for_label}}"
                                name="{{form.nombres.name}}" value="{{form.nombres.value}}">
                        </fieldset>
                        <fieldset class="my-1">
                            <label class="form-label" for="{{form.apellidos.id_for_label}}">Apellidos:</label>
                            <input class="form-control" type="text" id="{{form.apellidos.id_for_label}}"
                                name="{{form.apellidos.name}}" value="{{form.apellidos.value}}">
                        </fieldset>
                        <fieldset class="my-1">
                            <label class="form-label" for="{{form.rut.id_for_label}}">Rut:</label>
                            <input class="form-control" type="text" id="{{form.rut.id_for_label}}"
                                name="{{form.rut.name}}" value="{{form.rut.value}}">
                        </fieldset>
                        <fieldset class="my-1">
                            <label class="form-label" for="{{form.direccion.id_for_label}}">Direccion:</label>
                            <input class="form-control" type="text" id="{{form.direccion.id_for_label}}"
                                name="{{form.direccion.name}}" value="{{form.direccion.value}}">
                        </fieldset>
                        <fieldset class="my-1">
                            <label class="form-label" for="{{form.telefono.id_for_label}}">Telefono:</label>
                            <input class="form-control" type="text" id="{{form.rut.id_for_label}}"
                                name="{{form.telefono.name}}" value="{{form.telefono.value}}">
                        </fieldset>
                        <fieldset disabled class="my-1">
                            <label class="form-label" for="{{form.tipo_usuario.id_for_label}}">Tipo de usuario:</label>
                            <input readonly class="form-control" type="text" id="{{form.tipo_usuario.id_for_label}}"
                                name="{{form.tipo_usuario.name}}" value="{{form.tipo_usuario.value}}">
                        </fieldset>
                        <!-- <fieldset class="my-1">
                            <label class="form-label" for="{{form.username.id_for_label}}">Nombre de usuario:</label>
                            <input class="form-control" type="text" id="{{form.username.id_for_label}}" name="{{form.username.name}}">
                        </fieldset>
                        <fieldset class="my-1">
                            <label class="form-label" for="{{form.password.id_for_label}}">Contraseña:</label>
                            <input class="form-control" type="password" id="{{form.password.id_for_label}}"
                                name="{{form.password.name}}">
                        </fieldset> -->
                        <button class="btn btn-primary my-1" type="submit">Guardar</button>
                    </form>
            </article>
        </div>
    </div>

</main>
{% endblock content %}

templates/register.html
{% extends 'layout/base.html' %}

{% block title %}
Registro de usuarios - Inmuebles
{% endblock title %}

{% block content %}
<main class="d-flex justify-content-center align-items-center">
    <article class="card w-25 p-2 m-5 rounded-4">
        <div class=" p-4">
            <h2>Registro de usuario</h2>
            <form method="post">
                {% csrf_token %}
                {% if messages %}
                    {{messages.error}}
                {% endif %}
                <fieldset class="my-1">
                    <label class="form-label" for="{{form.nombres.id_for_label}}">Nombres:</label>
                    <input class="form-control" type="text" id="{{form.nombres.id_for_label}}" name="{{form.nombres.name}}">
                </fieldset>
                <fieldset class="my-1">
                    <label class="form-label" for="{{form.apellidos.id_for_label}}">Apellidos:</label>
                    <input class="form-control" type="text" id="{{form.apellidos.id_for_label}}" name="{{form.apellidos.name}}">
                </fieldset>
                <fieldset class="my-1">
                    <label class="form-label" for="{{form.rut.id_for_label}}">Rut:</label>
                    <input class="form-control" type="text" id="{{form.rut.id_for_label}}" name="{{form.rut.name}}">
                </fieldset>
                <fieldset class="my-1">
                    <label class="form-label" for="{{form.tipo_usuario.id_for_label}}">Tipo de usuario:</label>
                    <select class="form-select" type="text" id="{{form.tipo_usuario.id_for_label}}"
                        name="{{form.tipo_usuario.name}}">
        
                        {% for clave,valor in form.tipo_usuario.field.choices %}
                                {% if clave != 'administrador' %}
                                <option value="{{ clave }}">{{ valor }}</option>
                                {% endif %}
                        {% endfor %}
                    </select>
                </fieldset>
                <fieldset class="my-1">
                    <label class="form-label" for="{{form.username.id_for_label}}">Nombre de usuario:</label>
                    <input class="form-control" type="text" id="{{form.username.id_for_label}}" name="{{form.username.name}}">
                </fieldset>
                <fieldset class="my-1">
                    <label class="form-label" for="{{form.password.id_for_label}}">Contraseña:</label>
                    <input class="form-control" type="password" id="{{form.password.id_for_label}}"
                        name="{{form.password.name}}">
                </fieldset>
                <button class="btn btn-primary my-1" type="submit">Ingresar</button>
            </form>
        </article>
        </div>

</main>

{% endblock content %}